version: "3"
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command:
      - sh
      - -c
      - poetry run python -m main

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_NAME}

    ports:
      - "5432:5432"
