"""remove refresh token

Revision ID: 633d110a9451
Revises: 587573d4e1f5
Create Date: 2024-07-21 13:29:45.419644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633d110a9451'
down_revision: Union[str, None] = '587573d4e1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
