"""fixes models

Revision ID: a72d0cd22ba6
Revises: a1e52b68e613
Create Date: 2024-09-01 21:03:35.057445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72d0cd22ba6'
down_revision: Union[str, None] = 'a1e52b68e613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actions_user_id_fkey', 'actions', type_='foreignkey')
    op.drop_constraint('actions_company_id_fkey', 'actions', type_='foreignkey')
    op.create_foreign_key(None, 'actions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'actions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quizzes_company_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_company_id_fkey', 'quizzes', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.create_foreign_key('actions_company_id_fkey', 'actions', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('actions_user_id_fkey', 'actions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
